### ISSUE TITLE
Allow to hide (entities, tiles, sprites) which have the same layer.

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#100]
i'm talking about (entities, tiles, sprites) which have the same layer. For exemple if we have 2 ground tiles in low layer, we can't hide just one of them. the hide option (1/2/3 keys)  is used to hide all the tiles that have the same layer.

**Comment by christopho** [comment]
Duplicate of #96. Please don't open several identical bugs.
