### ISSUE TITLE
Shortcuts to switch between tabs

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#101]
Right tab: Ctrl + tab or Ctrl + page down
Left tab: Ctrl + Shift + tab or Ctrl + page up

**Comment by maxamine** [comment]
Ctrl + tab is better

**Comment by Diarandor** [comment]
I have a question/suggestion related to this. 

At present, is it possible to swap two tabs order when dragging with the left button of the mouse in the new version of the Editor? If not, maybe we should open an issue for that.
