### ISSUE TITLE
Can't open directly my quest in Solarus quest editor 1.4.4

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#102]
Under windows 8 i've changed the shortcut's properties such as you did in 21's episode to open directly my quest while opening Solarus quest editor but it dosen't work, i must do it manually each time i open Solarus quest editor . See the print screen bellow.

![1](https://cloud.githubusercontent.com/assets/14140919/9847364/46ddbba4-5ad0-11e5-8844-287e246514ee.jpg)

![2](https://cloud.githubusercontent.com/assets/14140919/9847418/99a8d47c-5ad0-11e5-885d-1db995480cb9.jpg)

**Comment by christopho** [comment]
The shortcut should be set to the solarus-quest-editor.exe file followed by the folder containing data.
Something like D:\solarus\solarus-quest-editor.exe D:\path\to\your\quest

**Comment by maxamine** [comment]
Youpiii it works. thks a lot christopho^^
