### ISSUE TITLE
Allow to group entities in the map editor

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#104]
Add a function allowing associating tiles that form the same entity in the map (for exemple tree's tiles)  using the properties of the right mouse button or by using the shortcuts (Alt+g to associate tiles and ctrl+alt+g to dissociate them).

**Comment by christopho** [comment]
I thought we already had this feature request but I can't find it. Yes, it will be useful. I think it should be called "Group" rather than "Associate".

**Comment by maxamine** [comment]
what about the shortcuts i proposed?

**Comment by christopho** [comment]
I don't know, we will see.

**Comment by christopho** [comment]
There is no shortcut using Alt, so I would prefer Ctrl+something and Ctrl+Shift+something.

**Comment by maxamine** [comment]
may be Ctrl+q and Ctrl+Shift+q

**Comment by Renkineko** [comment]
Ctrl+q is a standard to quit an application (like ctrl+w to close a tab), so I'm not sure about this.

**Comment by maxamine** [comment]
what about Ctrl+d to group or ungroupe entities, such as Ctrl+g to display or hide the grid?

**Comment by christopho** [comment]
I finally found the initial feature request, it was in the wrong repository. I just imported it here: #126. Closing this one as duplicate.
