### ISSUE TITLE
Allow to swap two tabs order (with left mouse button drag)

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus-quest-editor#107]
Allow to swap two tabs order when dragging with the left button of the mouse. This will be useful when several maps and other things are opened at the same time in the Editor.

**Comment by Diarandor** [comment]
Another solution would be to add two arrow buttons (left and right) to change the order of the current tab.

**Comment by christopho** [comment]
Dragging tabs is more standard.

**Comment by Diarandor** [comment]
Yes, you're right, dragging tabs will be better.

**Comment by oclero** [comment]
For dragging tabs, there is a built-in function
