### ISSUE TITLE
Crash when Solarus::Arguments' program_name is empty

### ISSUE THREAD

**Issue by daniloegea** [christopho/solarus-quest-editor#110]
Backtrace -> http://pastebin.com/VHvz6epe
PHYSFS_getBaseDir() is returning NULL. If I change solarus to call PHYSFS_init with a valid path instead of nullptr it works. Probably if Solarus::Arguments is instantiated with argc and argv (and argv[0] probably should has a full path to the executable) it'll work. 

I'm working on FreeBSD 11. I'd like to have a working port of solarus-quest-editor on our Ports Tree :)

**Comment by daniloegea** [comment]
I've created a small patch to address this issue on FreeBSD [1], it's working here. What do you think?

https://github.com/christopho/solarus-quest-editor/pull/112

**Comment by christopho** [comment]
This is now fixed.
