### ISSUE TITLE
Map editor: can't resize tiles from top or from left

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#111]
in Map editor the tiles are only resized from the bottom and right side. when i try to resize them from left or from top, it's resized from the opposite side. I have to move the tile to left or up and then resize it. (see print screens bellow).
it would be helpful if tiles are resizable from all sides. 

![1](https://cloud.githubusercontent.com/assets/14140919/10043411/be0afd56-61ea-11e5-94ea-14a5445ff451.jpg)

![2](https://cloud.githubusercontent.com/assets/14140919/10043413/c201471c-61ea-11e5-9439-eec85f0253fa.jpg)

**Comment by christopho** [comment]
But when you do that, how would the editor know if you want to resize to the left or shrink from the right?

**Comment by maxamine** [comment]
by calculating the initial position of the mouse (if possible of course). when the tile is selected, if the cursor is positioned on the right side of the tile, and click R and slides to the left it means we want to shrink it, and if the cursor is positioned on the left side of the tile and slides to the left it means we want to extend it to the left. What do you think?

**Comment by maxamine** [comment]
if it's not possible we can think of another solution or trick to perfect the resizing tool as you did for smart resizing. The point is to keep the idea because it can be very useful

**Comment by christopho** [comment]
I don't think that this a good solution. It is not intuitive to have 2 different behaviors depending on the initial position of the mouse. Users will be surprised, they would not understand the rule. They would have to know how it works, and it is hard to guess. The behavior would feel random.

But I completely agree that to extend to the left, it is a bit annoying to have to move the tile to the left first and then resize it.

Here is maybe another idea: Shift + R to resize to the left/top?

**Comment by maxamine** [comment]
very good feature. R for resizing and shrinking from right/bottom of the tile and Shift+R to do the same thing but from the opposite sides (top and left) of tiles. but it must also be valid for (smart resizing) when a group of tiles are selected.

**Comment by christopho** [comment]
Smart resizing multiple entities to the left will give me headaches, but I will try :)

**Comment by maxamine** [comment]
I do not think it would be more complicated if we add the Shift + R shortcut for resizing multiple entities left and up since version 1.5 already allows to limit resizing tiles by choosing (orizontal /vertical only)?

**Comment by christopho** [comment]
Completely other idea: resizing handles like this:
http://i.imgur.com/HoLypMq.png
Maybe both ideas can coexist?

**Comment by maxamine** [comment]
^^ i was thinking about the same idea, indeed it's more intuitive... and even more useful if we can do the same thing to both of (entity / multiple entities)^^

**Comment by maxamine** [comment]
later, this feature could be helpful for this one (see the link below). (not necessary but maybe^^)

https://github.com/christopho/solarus-quest-editor/issues/134

**Comment by mattias-p** [comment]
How about waiting for the mouse cursor to cross horizontal and vertical boundaries of the selection before choosing which sides to resize? If the cursor crosses the left side first, it starts resizing to the left. If the cursor then crosses the bottom side, it starts resizing the bottom left corner.

**Comment by maxamine** [comment]
@mattias-p  as @christopho said '' It is not intuitive to have 2 different behaviors depending on the initial position of the mouse. Users will be surprised, they would not understand the rule. They would have to know how it works, and it is hard to guess. The behavior would feel random.''

**Comment by maxamine** [comment]
@mattias-p 
as @christopho said,  It is not intuitive to have 2 different behaviors depending on the initial position of the mouse. Users will be surprised, they would not understand the rule. They would have to know how it works, and it is hard to guess. The behavior would feel random.

see this: 
 http://forum.solarus-games.org/index.php/topic,526.msg2603.html#msg2603:

**Comment by christopho** [comment]
Sometimes you resize by pressing R and the mouse may be anywhere in the screen.
And when you resize from the contextual menu after a right-click, it is always already on the right. So it cannot work.

**Comment by mattias-p** [comment]
@maxamine, I did read both this thread and the linked forum thread. But I didn't express myself clearly. I'm sorry about that. This is what I meant:

1. User presses R or uses the context menu. Present some feedback telling the user he's entered into resize mode. Nothing is being resized yet.
2. User moves cursor across the selection boundary (top, bottom, left or right). The crossed boundary starts following the cursor and now the selected tiles are resized in one dimension.
3. If user moves the cursor crosses across a boundary that's orthogonal to the one crossed in step 2, this boundary also starts following the cursor and the selected tiles are resized in two dimensions.
4. The user left-clicks or presses escape. The resize is committed or aborted.

I'm not sure what the feedback in step 1 ought to look like. Maybe like darkhog's illustration? Something that encourages the user to interact with the selection boundary in any case. But if those resizing handles are shown, then maybe they should work like resizing handles as well?

Whatever user interface is chosen, I think the resize functionality should be extended to work in all four diagonals (NE, NW, SW, SE) and not just two (NW, SE).

**Comment by christopho** [comment]
I am working on this feature request. First results show that I might change my mind. Maybe the resizing direction can be simply decided from the mouse position. This is more intuitive than I thought. It also allows to work with all four diagonals and not just NW/SE. For example, when the cursor is located on the bottom-left part of a selection, it feels normal that the selection extends from the bottom-left (and that the top-right part is the fixed point).

We don't even need to wait for the cursor to cross some boundaries as @mattias-p suggests. We can just decide from the mouse position when pressing R or showing the context menu. 

As future work, it will still be nice to additionally provide resizing handles.

**Comment by maxamine** [comment]
@christopho : That's exactly what i was talking about, i think it's intuitive but i'm not programmer and i dont know if it could be released. As you said @christopho , handles could be very useful not just for recizing, (see screenshot above)
