### ISSUE TITLE
Map editor: allow to unselect all entities

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#115]
Like there is "Select all", a shortcut to unselect all entities would be useful.
Currently, the user has to click on an empty space.

**Comment by alexander-b** [comment]
ESC should be mapped to 'unselect all'.

**Comment by christopho** [comment]
Escape will be used for #94.

**Comment by alexander-b** [comment]
As discussed on IRC, I think that ESC should be used both places. It's the same thing, conceptually. It's merely a distinction in unselecting a pattern vs. unselecting a tile. If you have selected tiles and then selected a pattern that you want to unselect, ESC could only unselect the patterns, forcing the user to hit ESC a second time to unselect the tiles. I.e. a simple LIFO approach.

We should so far as possible use ESC to mean "abort what I am *currently* doing", regardless of context, and only one operation should be aborted each time.

**Comment by christopho** [comment]
I disagree, they should be different shortcuts.

The current selection is not an operation in my opinion, it is more some data than a state. Escape should not remove it.

So here is the plan:

- Stop adding entities: Escape. Note that this means all ways of adding entities, not only by picking tiles from the tileset view, but also adding an entity from the entity toolbar and pasting entities. Really, this is not "unselect a pattern" but "stop adding entities". Adding entities keeps the current selection intact, so using the same shortcut to unselect things would be confusing.

- Unselecting everything: Shift + Ctrl + A. As often, the reverse of a shortcut can be the same one with Shift.

**Comment by maxamine** [comment]
Add a shortcut to unselect all
