### ISSUE TITLE
Tilesets editor craches when we delete a large number of tiles.

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#120]
When we select a large number of tiles selections in the tilesets editor and delet them in one click it takes too much time and craches in the end. To avoid the crach we have to remove tiles selections little by little.

**Comment by christopho** [comment]
I don't reproduce the issue. @maxamine do you still have the problem, and if yes, can you send me your project?

**Comment by maxamine** [comment]
Yes @christopho i still have the problem. check your emails box, i just send you a png source with its .dat file. when i try to select all tiles and delet them in one click the screen freezes and craches in the end.

**Comment by christopho** [comment]
Ok thanks
