### ISSUE TITLE
Crash when deleting a file that does not exist

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus-quest-editor#124]
If you delete the image and dat file of some sprite directly from the data (without using the editor), and later you try to delete that file from the editor, it crashes. You are forced to delete it from the project_db.dat directly, which is not good. (The editor is showing an "!" icon because the file is not found, but still it crashes.) 

I suppose that this could happen with other entities in the editor, but I have only checked this for sprites. (I have checked now that in the case of maps there is no crash.)

**Comment by christopho** [comment]
Cannot reproduce the crash. Can you give more details?

**Comment by Diarandor** [comment]
I have tested this and it seems to happens sometimes. I don't know what is producing the crash and it's hard to reproduce. I think it depends on the name of the file (with some file names it does no happen).

To reproduce it, duplicate some dat file of some sprite and rename it to ca.dat, then add it as a sprite in the editor, then close the editor, delete the dat file, open the editor and try to delete the sprite. Then I get a crash.

Since this seems too hard to reproduce I suggest to close the issue and forget about it. But still, it's a very strange crash.

**Comment by christopho** [comment]
I keep it open but I can't fix it immediately.

**Comment by wrightmat** [comment]
I've have had this crash pretty reliably when deleting resources from the tree after I've already deleted the files. Normally once I bring the program back up after the crash I can delete with no problems.
