### ISSUE TITLE
the tileset does not keep the same view when it is refreshed

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#129]
In map editor, when we presse the button update the tileset and as the scroll bar is down the window, the window displays the top of the tileset, it would be helpful if it keeps the same position?

**Comment by christopho** [comment]
This is annoying yes.

**Comment by maxamine** [comment]
the adjustment is not working all times . i can not reproduce the bug as much as i want , It Seems completly random, but Several times ( Especially when i modify the png) and i click on the refresh button, the tileset view doesn't keep the same scroll position.
