### ISSUE TITLE
Add refresh/update button for tilesets

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus-quest-editor#132]
Add refresh/update button for tilesets in the Editor.

**Comment by christopho** [comment]
You mean to refresh the PNG file of the tileset?

**Comment by Diarandor** [comment]
Yes, that's it.

**Comment by maxamine** [comment]
we have alreday an issue for this feature: #86

**Comment by Diarandor** [comment]
Oops, sorry. I did no see it.
Then I close this one.

**Comment by maxamine** [comment]
yes
