### ISSUE TITLE
Request: Changing the size of the work area.

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#135]
In the current version of sqe, enlarging or reducing the size of the work area adds or removes space only on the right and bottom of the map.
it would be more useful if we can lock a reference point to control the resized area (left / right and up / down). the lock is used to keep the proportions of the map, and the central point allows changing the size of the map in 2 directions when the lock is disabled, or 4 directions if the lock is activated. see the screenshot below :

![taille de la map](https://cloud.githubusercontent.com/assets/14140919/12019718/f33656fc-ad6b-11e5-883a-ea6e807b2aa7.png)

**Comment by maxamine** [comment]
Christopho: si t'as besoin des svg de la serrure et des points de référence je peux les préparer. juste fais la demande ^^

**Comment by christopho** [comment]
I don't think it is a very useful feature. It adds extra widgets for limited interest.
Resizing the map to the left/top would also change the coordinates of all entities of the map, so I prefer to let users resize to the right/bottom and then explicitly move entities, to better understand what they are doing.

**Comment by maxamine** [comment]
ok
