### ISSUE TITLE
Freeze in map editor when i do copy-past of all tiles in a big map into a new map

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#141]
when i do copy to all tiles in a big map (3632x2640) and past them in a new map, Map editor freezes and crashes (see the screenshot below):

![crash](https://cloud.githubusercontent.com/assets/14140919/13635884/860e873e-e5f6-11e5-951e-a57c9c929191.png).

check your inbox for data fil​es to r​eproduc​e th​e crash.

**Comment by christopho** [comment]
This is a performance regression of 1.4.5, since the entity selection in the map view is synchronized with the pattern selection in the tileset view.

**Comment by maxamine** [comment]
cool ^^
