### ISSUE TITLE
Add a transparency options for tiles of the map editor

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus-quest-editor#142]
Add a transparency option for tiles to the Quest Editor: either to the map editor or to the tileset editor.
There should be a variable in the Editor to set the amount of transparency of the tile. (If that variable is nil for a tile, the tile would be opaque, as they are now.)

This can be useful for water tiles with transparency (which are above other opaque tiles), for smoke tiles (which would have transparency too), etc.

I guess it will be necessary to allow transparency for normal tiles (although this could be added for dynamic tiles too).

**Comment by maxamine** [comment]
it will allow us to creat realistic maps, such as animated water with reflection and transparency. so we can see through water or through the tiles representing glass for exemple...

**Comment by christopho** [comment]
Note that it is already possible to put transparency in the PNG file.

**Comment by Diarandor** [comment]
Ok, I did not know that it was possible to use a transparency in PNG files. But in my opinion it will be more useful to have this as a property of tiles instead of separating tiles with transparency in different PNGs (which forces us to use different tilesets).

**Comment by christopho** [comment]
I mean a PNG image in ARGB format, where each tile can have different transparency values.

Like in this example: https://github.com/christopho/zelda_mercuris_chest/blob/dev/data/tilesets/dungeon_blue.tiles.png
Most tiles are opaque, but there are also semi-transparent water tiles.

**Comment by Diarandor** [comment]
I did not know about that ARGB format, that's interesting.
Then feel free to close this issue since it is not really necessary.

**Comment by christopho** [comment]
Ok, closing the issue.
