### ISSUE TITLE
Performance issue when loading big tilesets

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#143]
See the discussion here: http://forum.solarus-games.org/index.php/topic,560.msg2777/topicseen.html#new

The tileset is big, but opening it should never take so long (30 seconds reported).

**Comment by MetalES** [comment]
This is something I also faced long time ago by using a very large tileset (before 1.4) and on a low-end PC, I don't know if I can reproduce it, speaking about FFOmega, we don't really know that much of his computer's spec nor the program that are actually running on them (which can impact the load time).
Have you succeeded to reproduce the bug ?

**Comment by christopho** [comment]
The reported performance is actually when playing the game, not when using the quest editor.

**Comment by christopho** [comment]
Moved to https://github.com/christopho/solarus/issues/854
