### ISSUE TITLE
calculation of tile's repetitions

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#150]
when resizing a tile, the editor shoulds display a counter that calculates how many times the tile was repeated. the counter should display the number of (horizontal and / or vertical) repetitions or shows nothing depending on tile properties if it is repeatable (h / v) or not repeatable.
something like this: (see the screenshot bellow). 
using this new feature with the grid can save us a lot of time. (Feedback welcome)

![sans titre-3](https://cloud.githubusercontent.com/assets/14140919/14581384/a9bf95f0-03e3-11e6-89fa-6d50459dd651.png)

**Comment by maxamine** [comment]
the idea of the feature is great but it wouldn't work if many tiles are selected. but it can be applied if just one tile is selected

**Comment by christopho** [comment]
This kind of info should be displayed in the status bar, not in a new widget, and with more things than just the size.
