### ISSUE TITLE
Feature: Walking animation for non flat traversable grounds

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#151]
currently the editor offers several types of traversable grounds (water, grass, lava, scale) other types may be added:
when the hero walking on pebbles or sand, for example, it should go up and down to simulate the non flat ground effect. the walking animation will be more realistic ^^

**Comment by christopho** [comment]
A better way is to allow custom grounds, there is already an issue for that.

**Comment by maxamine** [comment]
it would be nice if we have some others kinds of grounds to avoid programming

**Comment by christopho** [comment]
There are already of lot of built-in grounds. Adding even more does not make a lot of sense, we cannot guess in advance everything quest makers will want.
