### ISSUE TITLE
Add a -1 layer

### ISSUE THREAD

**Issue by alexander-b** [christopho/solarus-quest-editor#161]
This is perhaps a crude hack, but it would be nice to have a layer beneath the layer that everything (e.g. the hero) acts on by default for background tiles (e.g. grass).

A simple use case scenario where this would be nice is when the user is working on some æsthetic thing, like making sure the tree line looks nice. It is likely that they'll need to B some part of the tree to make the line look nice. But now, they also need to select the background grass and B that too. Tedious!

The user can work around it already by just making everything layer 1, except for the grass. However, since the background tiles are the exception not the rule, they should be treated as such — with an exception. My suggestion here is simply a -1 layer.

**Comment by christopho** [comment]
I am not sure if I understand the problem.
But in 1.5, you can already have negative layers.

**Comment by alexander-b** [comment]
You often need to B something so that the graphics look nice. E.g. if you have two trees next to each other, with one on top of the other, it is imperative that the foreground tree is the top tree, and the background tree is the bottom tree. More often than not, the best way of doing this is to do B on the background tree. But if you have a bunch of grass background tiles, the tree will then disappear behind those as well. So you need to select the grass tiles and hit B on them, to make sure they are behind the background tree. This gets annoying the thousandth time you need to do it. :)

If the background grass was on a layer -1, this would never be a problem. And conceptually, it probably should be on a layer behind the hero. If this is fixed for 1.5, I guess you can close this.

Which commit do I need to use this feature? I'm on 8a2e18d1cb415b174d705d0cc58518f10b943074 from April 11th.

**Comment by christopho** [comment]
You can already create negative layers, just change the min layer value in the map editor.

**Comment by alexander-b** [comment]
Brilliant! Thanks.
