### ISSUE TITLE
Improve select mode in map view

### ISSUE THREAD

**Issue by alexander-b** [christopho/solarus-quest-editor#162]
I don't have a specific solution in mind, but here is the problem illuminated via example:

I have a bunch of background tiles, a 16x16 snow tile that's repeated across the entire map. Whenever I want to select something on the map now, I basically always end up selecting the background tiles instead. If I want to select multiple trees on my map, I have to start pressing the mouse outside of the map in order to not just select the background tiles. This is very annoying.

The workaround of moving the background tiles outside the map while working on the map is not satisfactory. It is quite tedious. And I'd have to move it back and forth all the time, because without them, gauging the æsthetic of the map would be very difficult.

**Comment by christopho** [comment]
Press ctrl or shift with your first click, and it will not select the background tile clicked.

There is also a feature request to "lock" entities, that is, make them unselectable somehow.

**Comment by alexander-b** [comment]
Great! Thanks a lot.
