### ISSUE TITLE
Add auto-focus mode for map editor

### ISSUE THREAD

**Issue by alexander-b** [christopho/solarus-quest-editor#173]
It would be good to have an auto-focus mode that moves the camera to highlight certain operations.

One very good example is undo. When undoing something, the camera doesn't move, and there's no confirmation outside of the map either. So did you undo something? What did you undo? Your only option at this stage is to zoom out and hit ^Z and S-^Z until you (hopefully) notice what you've undone. If the camera were automatically focussed on what you undid, this would be much better.

**Comment by oclero** [comment]
I don't know if this is a common user-interface pratice for graphical editors.
In text editors, this is common, but for example in Gimp, Adobe Photohshop or Illustrator, the camera does not unzoom then zoom to the location of the modification you undid. Do you have an example of something that could relate the map editor in SQE and that uses the functionality you desribe?

**Comment by alexander-b** [comment]
Anything. Add a tile in the bottom right, move the camera to the top left, hit ^Z.

I frequently edit stuff, move my camera elsewhere, go and eat a banana, come back, make a mistake, hit ^Z a few times to fix the mistake. Then I sometimes find that I accidentally undid one operation too many, and messed up the map in an entirely different spot.

**Comment by oclero** [comment]
I meant do you have an example of another software that does this because I've never seen this behaviour?

**Comment by alexander-b** [comment]
I'm not sure what the relevance is. This is an issue I am having with the Solarus Quest Editor, specific to how I use the Solarus Quest Editor.

But off the top of my head, Aseprite does this in some cases. E.g. If you have two animation frames, select frame 2, and the undo operation undoes something in frame 1, the program automatically brings that frame forward to my attention, preventing me from undoing something in a different frame by a mistake.

**Comment by Diarandor** [comment]
If you make a mistake in Aseprite you can always redo it if I am not wrong. I don't remember if that is possible with Solarus.

But the best of undoing and redoing is that Aseprite notifies you below of what has been changed. This is probably what should be done with the Editor: just notify something like: "a tile was removed/added" or "a tile was selected/unselected", etc.

**Comment by alexander-b** [comment]
I agree completely, and thought about filing a separate issue for that. I'll do that now!

**Comment by Diarandor** [comment]
I mean,  Aseprite writes below something like: "undid/redid [some type of action]". Would something like that solve your problem maybe?

**Comment by Diarandor** [comment]
Ok

**Comment by christopho** [comment]
Ok, closing this one then.
