### ISSUE TITLE
Feature Request: Audio description should be audio filename by default

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus-quest-editor#179]
I had to name over 400+ audio files by hand. It might be a good idea to make the audio file description the audio filename by default. The ability to change the description should be kept.

**Comment by Diarandor** [comment]
We should be able to choose the loop points for the music from the Editor, too.

**Comment by christopho** [comment]
Yes, but this is a completely different feature request.

**Comment by alexander-b** [comment]
I had the same thought myself, but I think this issue is too limited. I would like this to be the case for all resources. See #192.

**Comment by christopho** [comment]
Closing this one, it will be done for all resource types in #192.
