### ISSUE TITLE
Feature Request: Bitmap Font GUI Setup

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus-quest-editor#181]
The ability to select areas on bitmap font image files would increase the speed of the font set up process. A lot of fonts have different spacing and .tff packages can take quite a bit of time to create from bitmap images. A GUI setup that allows letter selecting would be great. Not only does it save time, but may give developers the motivation to make many fonts.

**Comment by alexander-b** [comment]
This is usually a non-issue with properly made fonts, but it could be a nice thing to have. It could be similar to the sprite editor. But it should probably not be high priority for now.

**Comment by Zefk** [comment]
There is no proper way to create in my opinion.

**Comment by christopho** [comment]
There is an issue to support bitmap fonts with variable width: https://github.com/christopho/solarus/issues/271
Characters will still all have the same space in the PNG file (it is just that they will be cropped if they have margins).

We don't want a complex editor to set up advanced things for bitmap fonts. User who wants advanced font features should use a proper TTF font.
