### ISSUE TITLE
Feature Request: Individual Small Tileset tabs 

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus-quest-editor#182]
Individual small tileset tabs would help to keep things neat and tidy. It is also a way to help the developer to quickly find certain pixel art. For example, a tab named trees can hold the tree tileset image. Naming the tabs would be a very nice addition, but simple alphabet letters could work too. (Naming might make tab length issues) "T" for "T"ree would be fine. Also, it can help avoid license issues between GPL Art and CC-BY pixel art. Separate tabs means that the image files can be on different image files, but will allow use on the same map without tileset change. This gives the developer the ability to layer the GPL art on the creative common art without license violations. What the code (functional data) does not apply to things based on beauty (non-functional data = image files or audio, but audio can easily be called with code.). I have much beautiful GPL pixel art that I cannot use due to this unless I keep one map just GPL license pixel art. This goes for the majority of other licenses as well.

**Comment by alexander-b** [comment]
First of all -- GPL is a software licence. If someone is using it for art assets, you should tell them to not do that. It isn't made for that and makes no sense for art assets.

Regarding your feature request -- I don't understand what you want at all. What do you mean by "small tileset tabs"? What are they? How do they look in the UI? How do they help? How do you organise them? What does this have to do with licensing at all?

**Comment by christopho** [comment]
You mean a tileset organized in multiple several PNG images?

**Comment by Zefk** [comment]
> First of all -- GPL is a software licence. If someone is using it for art assets, you should tell them to not do that. It isn't made for that and makes no sense for art assets.

You are asking me to email over 5,000 people to change their pixel art license from GPL to something else. No joke or exaggeration. Image files are **non-functional data** for beauty purposes, so it is okay.


> You mean a tileset organized in multiple several PNG images?

Yes, that way a GPLv3 license bushy tree top could be overlapped with a creative common 3.0  tree trunk to make a full tree without license violations. I can not put them on the same image without license violations. **Functional data** like programming code must do it with separate images files

-----------------------
Pretend that "A" tab is the current image tab for creative common 3.0 trees and "T" could be used for GPLv3 trees. 

![selection_001](https://cloud.githubusercontent.com/assets/19560764/15914909/b3543168-2d99-11e6-86b6-c51d9daea33d.png)

**Comment by christopho** [comment]
Too much complexity for the user (and developer :)) for very small usefullness. It is not recommend to mix different art licenses in the same tileset.

**Comment by alexander-b** [comment]
Zefk, yes I would email those over 1,000 people. Their licence choice makes no sense and isn't going to hold up in court. They are using a software licence on an image. You should email them and explain to them that they are doing themselves and their users a big disservice.

I would recommend they use CC-BY-SA-4.0.

**Comment by Diarandor** [comment]
alexander-b is probably right.
But I do not understand why opengameart and other similar websites allow GPL licenses for images, music and sounds.

**Comment by alexander-b** [comment]
I guess they haven't actually read it. :)

**Comment by Zefk** [comment]
@alexander-b 
> Zefk, yes I would email those over 1,000 people. 

I do not have time to collect that much emails. Please let me know about your email journey on many members on opengameart.org. Most of the time it will not go to court. The cost of court fees and time will not be worth it. Online communities or the services normally deal with these problems.  I will respect their wishes and use GPL because it does not hurt anything because a lot of the license rules will not apply to non-functional data. I do not think it makes much sense, but free is free to me.

@christopho 
> Too much complexity for the user (and developer :)) for very small usefullness. It is not recommend to mix different art licenses in the same tileset.

I was really hoping for the tab feature. Well, I guess I can work without it.
