### ISSUE TITLE
Feature Request: Adding animation to multiple 8x8 blue borders

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus-quest-editor#190]
It would be nice if I could highlight many blue borders and set the animation for them all at once.
![highlight many blue borders and set animation](https://cloud.githubusercontent.com/assets/19560764/15802729/72ea2ce8-2a71-11e6-81d6-a3c4ffe3ed43.png)

**Comment by christopho** [comment]
You can already if you right click.
