### ISSUE TITLE
Bug (Jumpers) when negative layers are used

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#194]
currently, using positive layers, when the hero uses a jumper, it is transported from the original ground layer to layer of the ground on which it is landing.
But when placing a jumper between a ground of the upper positive layer and a lower negative layer (example 1 and -1), or a ground of the upper negative layer and a lower negative layer too (example -1 and -2), when the hero jumps it keeps the original layer.

**Comment by christopho** [comment]
Nice find, thanks

**Comment by christopho** [comment]
But wrong repository
