### ISSUE TITLE
Crash when creating a block with a missing sprite

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#195]
See http://forum.solarus-games.org/index.php/topic,675.msg3459.html#msg3459
Same problem reported with crystals and crystal blocks.

**Comment by SciverSatoh** [comment]
To reproduce the error, I simply load or create a project with no predefined `sprites/entities/block` sprite, and try to add a block in the map editor. The entire solarus quest editor application should immediately terminate with an error.
