### ISSUE TITLE
Install Phase Missing

### ISSUE THREAD

**Issue by Nate-Devv** [christopho/solarus-quest-editor#196]
The CMake configuration doesn't seem to be able to install the quest editor.  This doesn't effect most users, but I think it is the reason that the .debs that I tried to make for the editor were empty.  I found this issue when trying to create a nix package for the editor (https://github.com/Nate-Devv/nixpkgs/commit/67f3004fdc8e10c7b7e5037d7a621d4f61f0a3db).

**Comment by Nate-Devv** [comment]
I think this is an issue in 1.4.5 that was fixed in the current git master, closing issue.

**Comment by christopho** [comment]
Yes, make install works in the current git dev branch.
