### ISSUE TITLE
How to install on ubuntu? Erro...

### ISSUE THREAD

**Issue by kholyphoenix1** [christopho/solarus-quest-editor#199]
Hello, 

I am unable to install on Ubuntu this Solarus Edit.
Could anyone help me?

Info: 
"Get the repository with: curl -s https://packagecloud.io/install/repositories/NateDevv/solarusDebs/script.deb.sh | sudo bash. Then, install solarus and solarus-editor. Or manually browse packages."

Thank you!

**Comment by christopho** [comment]
@Nate-Devv is this info still correct?

**Comment by kholyphoenix1** [comment]
That's what is showing on the link.
I'm don't know... 
Thanks!

**Comment by Nate-Devv** [comment]
I haven't been able to build an 1.4.5 editor, period, whether on a package or otherwise.
There are still packages up there, but the only ones that are still up are zoned for Debian Jessie and Ubuntu Trusty. https://packagecloud.io/NateDevv/solarusDebs

**Comment by Nate-Devv** [comment]
However, I've been having constant bandwidth problems with packagecloud, and no money to upgrade bandwidth, so I'm going to re-create my source packages (because I don't have them on my machine), and upload them to a ppa, which should have more bandwith. I'll report back here when I've finished.

**Comment by kholyphoenix1** [comment]
Thanks a lot!

**Comment by Nate-Devv** [comment]
Created the ppa and uploaded it. With any hope, the packages will be available there soon. https://launchpad.net/~nate-devv/+archive/ubuntu/solarus

**Comment by Nate-Devv** [comment]
Solarus editor 1.4.5 don't play well together. Not sure if 1.5 editor will have the same issues, but we'll see when the release comes out.  I have a temporary fix on the forum post, which is basically to just compile the editor with the solarus package installed.

**Comment by kholyphoenix1** [comment]
Nate-Devv, thanks a lot!

**Comment by Nate-Devv** [comment]
No problem, glad I could help!
