### ISSUE TITLE
Inaccurate dependency

### ISSUE THREAD

**Issue by mattias-p** [christopho/solarus-quest-editor#20]
[QSignalBlocker](http://doc.qt.io/qt-5/qsignalblocker.html) is used in several places. Either the dependency on Qt in the compilation instructions should be bumped to 5.3, or some kind of fallback should be provided.

N.B. After removing all references to QSignalBlocker I was able to compile with Qt 5.2. The editor even starts and I can click on things.

**Comment by christopho** [comment]
I did not notice that QSignalBlocker was so recent. Thanks for the report!
