### ISSUE TITLE
Build Error Debian Jessie with latest Solarus

### ISSUE THREAD

**Issue by Nate-Devv** [christopho/solarus-quest-editor#208]
Attempted compile on Debian Jessie fails. The mentioned header file was generated to solarus/build/gui, but it seems to not use it.

`cmake -DSOLARUS_INCLUDE_DIR=../../solarus/include -DSOLARUS_LIBRARY=../../solarus/build/libsolarus.so -DSOLARUS_GUI_INCLUDE_DIR=../../solarus/gui/include -DSOLARUS_GUI_LIBRARY=../../solarus/build/gui/libsolarus-gui.so ..`

`Building CXX object CMakeFiles/solarus-quest-editor.dir/src/widgets/music_chooser.cpp.o
In file included from /home/nathangl/git/solarus-quest-editor/build/ui_main_window.h:24:0,
                 from /home/nathangl/git/solarus-quest-editor/include/widgets/main_window.h:22,
                 from /home/nathangl/git/solarus-quest-editor/src/widgets/main_window.cpp:23:
/home/nathangl/Documents/Development/C++/repos/solarus/gui/include/solarus/gui/console.h:21:24: fatal error: ui_console.h: No such file or directory
 #include "ui_console.h"
                        ^
compilation terminated.
CMakeFiles/solarus-quest-editor.dir/build.make:1357: recipe for target 'CMakeFiles/solarus-quest-editor.dir/src/widgets/main_window.cpp.o' failed
make[2]: *** [CMakeFiles/solarus-quest-editor.dir/src/widgets/main_window.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/solarus-quest-editor.dir/all' failed
make[1]: *** [CMakeFiles/solarus-quest-editor.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2`

Interestingly, removing the SOLARUS_GUI_LIBRARY flag allows the editor to get to 52% (the above is at about 4%), but the build still fails for a similar reason (the file at fault is widgets/map_editor.cpp in that case).

**Comment by christopho** [comment]
When you don't install Solarus, the compilation is more complicated because of headers generated at compilation time (config.h and some Qt files).

More complicated but possible. This should work:
-DSOLARUS_INCLUDE_DIR=../../solarus/include;../../solarus/build/include
-DSOLARUS_GUI_INCLUDE_DIR=../../solarus/gui/include;../../solarus/build/gui

**Comment by Nate-Devv** [comment]
Ok. I tried what you said, but while it got further, it did eventually stop. I'm going to try installing Solarus.

**Comment by christopho** [comment]
What was the next error?

**Comment by Nate-Devv** [comment]
This is using commit solarus/5e804154da5457d985106bd9e0803f33e860f2a2, the second to last.
```
[100%] Building CXX object CMakeFiles/solarus-quest-editor.dir/solarus-quest-editor_automoc.cpp.o
In file included from /home/nathangl/git/solarus-quest-editor/build/solarus-quest-editor_automoc.cpp:2:0:
/home/nathangl/git/solarus-quest-editor/build/moc_dialogs_model.cpp:9:97: fatal error: ../../../Documents/Development/C++/repos/solarus-quest-editor/include/dialogs_model.h: No such file or directory
 #include "../../../Documents/Development/C++/repos/solarus-quest-editor/include/dialogs_model.h"
                                                                                                 ^
compilation terminated.
CMakeFiles/solarus-quest-editor.dir/build.make:2829: recipe for target 'CMakeFiles/solarus-quest-editor.dir/solarus-quest-editor_automoc.cpp.o' failed
make[2]: *** [CMakeFiles/solarus-quest-editor.dir/solarus-quest-editor_automoc.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/solarus-quest-editor.dir/all' failed
make[1]: *** [CMakeFiles/solarus-quest-editor.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Nate-Devv** [comment]
I also get this error using a system installed version of Solarus (on the latest at the moment commit), without specifying any flags (so that means that they're all auto-inferred in 1.5?).

**Comment by Nate-Devv** [comment]
I tried to recompile on the latest commit, still getting the same error.  I'm going to see if the package tools make a difference.

**Comment by Nate-Devv** [comment]
The packaging tools don't have the problem, so it might be ok.
