### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Maxs1789** [christopho/solarus-quest-editor#21]
It would be great to have a settings window for the editor.

Settings are useful for all editors, here are some example of setting :
- _font_ (size, highlight color, etc ...)
- _background_ (background color for all graphics views)
- _grid_ (size, style, etc ...)
- Maybe the _step_ of some spinboxes
- etc ...

Maybe that the editor can use __PHYSFS__ to store settings in the user directory (`.solarus-quest-editor` per example) like the engine.

Now, for the format of the settings file, I don't know if it is better to use _Lua_ or _XML_.

**Comment by Maxs1789** [comment]
I don't close this issue because the settings dialog isn't finished yet !

**Comment by christopho** [comment]
I am closing the issue now that the dialog is part of the 1.4 release. Feel free to open new issues for additional settings you want to add.
