### ISSUE TITLE
The edit entity dialog allows to set illegal sizes

### ISSUE THREAD

**Issue by Maxs1789** [christopho/solarus-quest-editor#23]
Il est possible de donner aux entités n'importe quelle taille multiple de 8 (mais supérieur à celle du pattern) alors qu'on devrait (je pense) pouvoir ne donner qu'une taille qui soit multiple de celle du pattern.

Je ne sais pas si ce bug concerne également le moteur, mais de son coté il n'indique aucune erreur mais n'affiche pas le tile tel qu'il est dans l'éditeur. Par exemple pour un tile de 32px de hauteur, si je lui donne une hauteur de 40px le moteur affichera ce tile sur 64px de hauteur (pareil pour les collisions).

**Comment by christopho** [comment]
This is only possible from the edit entity dialog box. But still a bug, yes.

**Comment by Maxs1789** [comment]
I see three ways to solve this issue:

1. Check values when closing the dialog and show an appropriate error message.

2. Detect value changes then force the value to be a multiple of the base size: 
`round(value / size) * size`.

3. Use suffix of QSpinBox to display `n * size` where `n >= 1`, so the user cannot set arbitrary values.

I like the last one because it's very simple and gives informations about the base size.

**Comment by christopho** [comment]
Even if 1 was the behavior in the old editor, I'd say 2, like we do for the entity name: we silently change it it is already used.
3 is not an option to me.

**Comment by Maxs1789** [comment]
Ok, and what do you think about the idea to consider the **ResizeMode** in the edit entity dialog box?

- **ResizeMode::NONE**: disable two spin boxes.
- **ResizeMode::HORIZONTAL_ONLY**: disable the height spin box.
- **ResizeMode::VERTICAL_ONLY**: disable the width spin box.
- **ResizeMode::SQUARE**: detect when one of these spin boxes change and set the same value to the other one.
- **ResizeMode::SINGLE_DIMENSION**: the more complex, I don't know how to handle this case.
- **ResizeMode::MULTI_DIMENSION_ONE**: nothing to do.
- **ResizeMode::MULTI_DIMENSION_ALL**: nothing to do.

---
Also, what about the [EntityModel::is_size_valid()](https://github.com/christopho/solarus-quest-editor/blob/master/src/entities/entity_model.cpp#L1151) method? 

I think we should replace
```cpp
if (width % 8 != 0 || height % 8 != 0) {
  return false;
}
```
by
```cpp
if (width % base_size.width() != 0 || height % base_size.height() != 0) {
  return false;
}
```
It seems to me that width and height of the `base_size` are always multiple of 8.

**Comment by christopho** [comment]
Good ideas. For ResizeMode::SINGLE_DIMENSION: detect when one of these spin boxes change and set the base size to the other one.
Ok for the is_size_valid() change but first we need to check all callers.

**Comment by Maxs1789** [comment]
This is done for **ResizeMode** constraints!

But I realized that in this context, the modes **SQUARE** and **SINGLE_DIMENSION** aren't possible because they don't corresponds to a **TilePatternRepeatMode**.

**Comment by Maxs1789** [comment]
All done!

Commited in master:
- 057a792567063efe2ee28931ce5895e47be83eab
- f5265b477e623dac95ff860a9e5ed5a57539361a
- 5586e6714139c8ba2401fb3ad8735d001354b656
- e01c56eecee295550600d9fbbfce03261c9ffc6b
