### ISSUE TITLE
No context menu when right-clicking empty space

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#26]
Bug report from @Tjompalompa:
Right clicking on an empty space doesnt bring up a menu.
Solarus 1.4

**Comment by christopho** [comment]
This is on purpose. What do you suggest to put in a context menu in this situation?

**Comment by Tjompalompa** [comment]
To be clear, I'm referring to an emtpy (white) space in the map view/editor specifically. Solarus 1.3 brought up "create" and "paste" when right-clicking in that context.

**Comment by christopho** [comment]
Ok. I removed "create" because I thought it was not used, but if you find it useful I can put it back. And for "paste", I guess you are right.

**Comment by Maxs1789** [comment]
Commited in master (e13ec44f50bb90677479d8853c25dae58c9d34ac).

I've let all the common actions even if they are disabled (cut, copy and paste).
