### ISSUE TITLE
Map editor: allow to change the pattern of existing tiles

### ISSUE THREAD

**Issue by Zefk** [christopho/solarus-quest-editor#280]
It would be nice to change tile patterns and it would be a cool unique feature. If someone wanted to select "only" 50 of the same patterns on the map and change them, then this would be a useful feature. Also, maybe the tiles are super long. It would be a pain to select tiles and resize them to match the previously placed tiles.

I edited some graphics in Gimp to show what I mean:

Convert tile pattern to >
![selection_002](https://cloud.githubusercontent.com/assets/19560764/26555504/3117c5e8-444a-11e7-8bdc-0be289d3c3a3.png)

Type name of pattern id:
![selection_004](https://cloud.githubusercontent.com/assets/19560764/26555506/313adbbe-444a-11e7-8d63-a3ed83761cbb.png)

Pattern changed:
![selection_005](https://cloud.githubusercontent.com/assets/19560764/26555505/3135c570-444a-11e7-9fe2-9d509b12ee39.png)

**Comment by Diarandor** [comment]
This would be very useful. But note that this cannot be always used because some patterns cannot be "repeated" in certain ways.

**Comment by christopho** [comment]
So it is more "Change pattern" than "Convert pattern". I agree, it is a very useful feature.
The user would be able to change the pattern of some tiles without having to delete and recreate them.
