### ISSUE TITLE
Patterns in the tileset editor cannot be deslected once selected

### ISSUE THREAD

**Issue by ffomega** [christopho/solarus-quest-editor#289]
Tile patterns can be selected using "shift+click", but once multiple patterns are selected, you are unable to deselect any of them unless you deselect them all and start over.  This bug is noticed as of the June 21, 2017 build of Solarus.

**Comment by Maxs1789** [comment]
Not in the last version of the project (see commit fa28e56b856fdc5fc4381e170d15ab5476ca0c4c)

**Comment by christopho** [comment]
Ok I will just update the snapshot then. Thanks!
