### ISSUE TITLE
Tileset Pattern countours appear as a rectangle around selected tiles

### ISSUE THREAD

**Issue by ffomega** [christopho/solarus-quest-editor#290]
When selecting multiple patterns, which are not of a square or rectangular shape, the 'yellow' outline remains a rectangular shape.
![rectangle](https://user-images.githubusercontent.com/20507967/29240217-146dd9ac-7f26-11e7-906e-e9107605fe91.png)

**Comment by Maxs1789** [comment]
Not in the last version of the project (see commit 6348405848e65508854ffbb2f8f172b7afa2f026)

![capture du 2017-08-12 13-43-16](https://user-images.githubusercontent.com/573681/29240411-f25c9d64-7f64-11e7-89c8-a094f5abdc51.png)
