### ISSUE TITLE
Tile patterns that overlap existing patterns prevent them from being moved

### ISSUE THREAD

**Issue by ffomega** [christopho/solarus-quest-editor#291]
When selecting multiple patterns you wish to move in to another location, they can only be moved to a completely empty space on the tileset.  If there are any patterns in the way, even if there are gaps in the selected patterns, you are unable to move the patterns to the desired location (the example image shows obstructing patterns in pink for reference)
![cannot move](https://user-images.githubusercontent.com/20507967/29240232-71ad27f8-7f26-11e7-9c7a-13e93845895e.png)

**Comment by Diarandor** [comment]
I thought it was impossible to create overlapping patterns, at least directly from the editor...

**Comment by christopho** [comment]
It is, but in this case there is no actual overlap so the move should be accepted.

**Comment by Maxs1789** [comment]
Like for #290, in the last version of the project you can do that !
