### ISSUE TITLE
Bug?! Solarus Quest Editor 1.6 uses too much memory

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#306]
Not sur if it's a bug but when i used the solarus editor 1.6, it took too much memory. I tested the 4 snapshots of version 1.6
see the screenshot below:

![sans titre-1](https://user-images.githubusercontent.com/14140919/30619034-19e0fd0a-9d95-11e7-9acc-7858b8bf8e55.png)

**Comment by Zeldaforce** [comment]
Après avoir investigué il se trouve qu'on ne libère pas du tout la mémoire quand on ferme une map. Encore pire, si on ouvre une map fermée qui était déjà ouverte au préalable, on consomme encore plus de mémoire. (Autant que si deux maps ouvertes)
