### ISSUE TITLE
Sprite editor: the origin should be 8,13 by default

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#307]
Most entities want an origin of 8,13. The default value set by the editor is the center but is never the correct one.

**Comment by Diarandor** [comment]
Just an idea: there could be a button with the text "Default origin", that would replace the value with the "default built-in origin" (computed with the same algorithm that you usually use for that).

> Uh, don't ask me what "default origin" means, I'm just a kid!
😆
