### ISSUE TITLE
Request: add fast replacement for tiles

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus-quest-editor#309]
Feature request: add fast replacement for tiles.
This is just an idea, which is not prioritary for now, but could be very useful someday.

Example: For instance, if we are testing some ground/wall tiles and, after creating a map, we decide to use different patterns of the same tileset for the same grounds/walls. The only way to do that now would be to replace the tiles one by one  directly, which would be a pain.

Idea: The idea is the same as the option "replace color" in pixel-art editors, but in our case we are not working with colors, but with tiles instead.

Feature explanation: In the map editor, when a map is open, in the context menu of a tile (or a tile pattern) we could add an option "replace ALL by". If the user clicks on that option and then on a new tile pattern, all the tiles on the map with the old tile pattern will be replaced with tiles that have the selected tile pattern, and with the same properties (position, layer, size, name, etc). We could require the new and old tile patterns to be compatible (in some way) to do this. Some key-shortcut will be very useful to do this with two clicks.

**Comment by christopho** [comment]
Is it not a duplicate of #280?

**Comment by Diarandor** [comment]
Oops, you are right.
