### ISSUE TITLE
Door sprite not updated when changing the direction

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#32]
Bug report from linky:
http://forum.solarus-games.org/index.php/topic,253.msg843.html#msg843

Hello,

I'm trying the new editor 1.42 that is really nice and a big improvement to the previous one.

I believe there is a little bug with door item at least on my configuration. When you use contextmenu to change its direction (ie left to right), the door's icon is not updated immediatly. To make it change to the new direction you have chosen you have to go in its property pannel by double clicking on this door icon, where you can see that the new direction has really been changed but not visualy applied, and then make ok. This makes the door icon takes the good direction.

**Comment by Maxs1789** [comment]
Same issue for all these entities:
- Enemy
- NPC
- Block
- Stream

I think that's the case for all entities which have a sprite.

**Comment by Maxs1789** [comment]
Commited in master (0f7d2e3e151cfb10faeff0271f616c1dcc81592c).
