### ISSUE TITLE
feature: convert tiles to entities (chest, door, stairs...)

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#321]
in addition to the option (convert to dynamic tile) it would be useful to be able to convert tiles directly into (doors, stairs chest and so...) so we could add entities more easily directly from the tileset.
each converted tile will take properties of the entity to which it is converted.
this feature can be added to the right button like this:
convert to =>
      * Chest
      * Dynamic tile
      * Door
      * Stairs

**Comment by Diarandor** [comment]
I think that this is not possible because entities usually use sprites instead of tilesets.

**Comment by christopho** [comment]
As the name suggests, tilesets are for tiles ;)
