### ISSUE TITLE
Tileset editor: the pattern rectangle is no longer red when overlapping existing patterns

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#34]
In the editor < 1.4, when you create or move a pattern in an already occupied place, the rectangle became red instead of yellow. This was useful to indicate to the user if the action is possible or not.
In Solarus Quest Editor 1.4.2 the rectangle stays yellow.

**Comment by Maxs1789** [comment]
Commited in master (3d2cb9ecf6f1bd7757331bc165e79dad7e86cf67) for the `MOVING_PATTERN` state.

But how to do for the `DRAWING_RECTANGLE` state? If the selection overlaps patterns in this state, these patterns are selected. I don't see in what cases the selection must be red.

**Comment by christopho** [comment]
Relevant question, because in the old editor there was no selection by rectangle in the tileset editor. So I think you are right: since patterns get selected, the user naturally sees that the rectangle is a selection rectangle a not a rectangle for a new pattern. Let's keep it this way, it is better than the old editor.

**Comment by christopho** [comment]
Merged in 1.4.3. Thanks!
