### ISSUE TITLE
Quest properties editor: cannot undo on the 'write directory' field

### ISSUE THREAD

**Issue by Maxs1789** [christopho/solarus-quest-editor#36]
If we put an empty string on the write directory field, the undo action doesn't work.

The bug is due to the `write directory` which cannot be empty (see the [set_write_dir](https://github.com/christopho/solarus-quest-editor/blob/master/src/quest_properties.cpp#L108)).

**Comment by christopho** [comment]
Note that it is a bug if the write_dir field cannot be empty.
The doc says that write_dir is optional: http://www.solarus-games.org/doc/latest/quest_properties_file.html

**Comment by Maxs1789** [comment]
Commited in master (b4ae60008b46872a267ca95243b0b9ebc9fc660a).
