### ISSUE TITLE
Map editor: cannot redo on the 'world' field

### ISSUE THREAD

**Issue by Maxs1789** [christopho/solarus-quest-editor#37]
If we do several changes on the `world` field, and that we undo these changes, we cannot return to the last state.

**Example :**
- set a world, by example `world` (change focus to apply the action)
- uncheck the check box
- recheck the check box
- change the value, by example `world2` (change focus to apply the action)
- undo four times

and you cannot return to the state `world2`.

**Comment by Maxs1789** [comment]
This bug is more difficult to reproduce since merge of `line_edit` branch (1fa407d9ad84366a22f504a22d000218d8fbbbf3) but it still exists.

In all cases, it isn't produced at each times and I don't know exactly why.

**Comment by christopho** [comment]
I cannot reproduce this bug, and it is old enough to be probably fixed, especially now that the line_edit work was reverted.
Please reopen if you still have the problem.
