### ISSUE TITLE
Add a button to open the script of the current map

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#39]
When a map editor is open, there should be a button and/or a keyboard shortcut to switch to the script editor of the map.

**Comment by Maxs1789** [comment]
What keyboard shortcut use to do that ?

**Comment by christopho** [comment]
Maybe F4? And it would switch between the map and the map script, both ways. Like .h / .cpp in your favorite IDE.

**Comment by christopho** [comment]
Closing this issue since the button is now available in 1.4.4.
Created a new one for the keyboard shortcut: #75
