### ISSUE TITLE
Undo/Redo Shortcuts

### ISSUE THREAD

**Issue by Maxs1789** [christopho/solarus-quest-editor#40]
In any editors, shortcuts `Ctrl+Z` and `Shift+Ctrl+Z` allow to undo and redo, but if a field is focused (like a SpinBox or a LineEdit) it doesn't work.

**Comment by christopho** [comment]
Closing the issue because
- It works well on QLineEdit (maybe it did not on LineEdit, but this was reverted)
- If it does not work on QSpinBox, that's a Qt behavior that we won't change.
