### ISSUE TITLE
Dialogs editor: the last line is not displayed

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#45]
The last line of a dialog is not displayed when running the game. I'm currently inserting an empty line at the end of each message as a workaround.

**Comment by Maxs1789** [comment]
I can't reproduce this bug, for me all the lines are correctly displayed.

Can I have more details?

**Comment by Zakarisz** [comment]
I have the same bug : with no blank line at the end of a dialog, the code produced in dialogs.dat is
```
dialog{
  id = "test.hello",
  text = [[
hello world]]
}
```
instead of
```
dialog{
  id = "test.hello",
  text = [[
hello world
]]
}
```

**Comment by christopho** [comment]
Yes, this is the bug indeed.
The code produced should be
    dialog{
      id = "test.hello",
      text = [[
    hello world
    ]]
    }

**Comment by christopho** [comment]
This is actually a limitation of existing dialog box scripts. They all assume that the text ends with a new line and don't behave correctly when it is not the case. So to keep compatibility with them, let's add a new line if not present when writing the dialog file.

**Comment by christopho** [comment]
Fixed in https://github.com/christopho/solarus/commit/53064b68a578c4d0b08321dbb3526960677eb802 (the Solarus library is responsible of saving data files).

**Comment by christopho** [comment]
I also specified it in the doc: https://github.com/christopho/solarus-doc/commit/a14bcaf0c638d207258e20dc84f0eb83f67a5762
