### ISSUE TITLE
Dialogs editor : crash when trying to compare dialogs with empty entries.

### ISSUE THREAD

**Issue by PhoenixII54** [christopho/solarus-quest-editor#48]
When creating dialogs, if you create an empty string and try to compare it with another language, the editor crashes, and you can not access that file anymore until manually adding text for that particular id -or removing it-.

**Comment by Maxs1789** [comment]
The bug comes from the engine that does not allow empty text in dialog data files.

It's fixed in this [commit](https://github.com/christopho/solarus/commit/371b44675b9b04cd214c99a0bbba522b2753a0f3).

**Comment by christopho** [comment]
Reopening the bug because we need to update the changelog and the doc.

**Comment by Maxs1789** [comment]
I updated the doc and the changelog. (christopho/solarus@4204bc4a6c5c8fbb04832b909c137b34b5e52e10, christopho/solarus-doc@9d003aa1f92cf249a46b9ae80c9087f728fadef0).

But I keep this issue open, because the bug is not solved for the `1.4.3` version.

**Comment by christopho** [comment]
Ok, thanks!

**Comment by Maxs1789** [comment]
Committed in master (3b00cdac718822d18a907853ac9e32cf1326414e).

**Comment by christopho** [comment]
Merged in 1.4
