### ISSUE TITLE
Problem when displaying comments (unimportant)

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus-quest-editor#63]
In the text editor of the Solarus Quest Editor, if a block comment starts with "--[[" and closes with "]]", the text is green after the closure. (This does not happen if you close the comment with "--]]".)

Another problem is that, when using "---[[" and "--]]", there is not a block comment, but the text remains green. The syntax "--[[" ... "--]]" is very commonly used in Lua, to comment/uncomment a text block changing "--[[" with "---[[". See http://www.lua.org/pil/1.3.html

**Comment by Maxs1789** [comment]
And it does not take into account where you put `=`, like this:
```lua
--[==[ a multi lines comment ...
print("...")
--]==]
```
Also for strings:
```lua
local str = [==[
a multi lines string
...
]==]
```

**Comment by christopho** [comment]
I only fix the first problem of this issue: the rest of the line remaining green after --]].

The other two cases are not supported yet:
---[[  and --[==[
(you can open new issues for them if you need).
