### ISSUE TITLE
Ctrl+F don't display Find Dialog

### ISSUE THREAD

**Issue by Zakarisz** [christopho/solarus-quest-editor#65]
In the editor, when I do a Ctrl+F, the character "f" is written instead of displaying the find dialog.

**Comment by Zakarisz** [comment]
After an update and a make, it works.
I don't know if the problem was on my computer or if the bug is fixed.

**Comment by christopho** [comment]
Ok, it was probably a problem on your computer then because we never reproduced it. Thanks for giving the update, this saved time for everyone :)

**Comment by Zakarisz** [comment]
Désolé, je continue en Français. Je suis trop rouillé en anglais pour me lancer dans de grandes explications.

En fait, j'ai 2 machines de dev (Debian et Ubuntu). Sur ma Debian ça marche mais pas sur Ubuntu.
Mais le problème ne s'arrête pas là, je n'avais pas fait attention que je n'ai pas non plus de barre de menu.

![capture du 2015-07-15 12 02 39](https://cloud.githubusercontent.com/assets/1327614/8696334/b7434202-2aeb-11e5-9611-fb6772fe8af0.png)

Je me demande s'il n'y a pas un problème avec une version de lib pas tout à fait compatible.
J'ai lancé l'éditeur via un terminal pour voir s'il y avait des erreurs qui s'affichaient, mais il n'y a rien.

**Comment by christopho** [comment]
Sous Ubuntu avec Unity la barre de menu des fenêtres est généaralement séparée, affichée dans la barre supérieure de l'écran.

**Comment by Zakarisz** [comment]
Je n'utilise pas unity, mes deux bureaux (Debian et Ubuntu) sont sous OpenBox
