### ISSUE TITLE
When a translation is missing, show a red mark also on parent nodes

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#68]
In the dialogs editor and in the strings editor, when an item is not translated yet, its icon in the tree has a red mark. All its parent nodes should also have the same mark so that we know where translation work has to be done.

**Comment by Maxs1789** [comment]
Commited in master (ab3b0986dddd2c30cfb26a892b2d100420af9da2).

**Comment by christopho** [comment]
Thanks!
