### ISSUE TITLE
Crash when saving a tileset that was empty [Debug]

### ISSUE THREAD

**Issue by Maxs1789** [christopho/solarus-quest-editor#77]
With the editor compiled in debug mode, if we try to save a tileset with new tiles and that this tileset was empty before, the program crashes:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Abandon (core dumped)
```

**Comment by christopho** [comment]
Fixed in Solarus 1.5.
I was only affecting 1.5, not 1.4.
