### ISSUE TITLE
Allow to play musics and sounds directly in editor

### ISSUE THREAD

**Issue by christopho** [christopho/solarus-quest-editor#8]
From @Renkineko:

Sometimes, you don't really remember what is the name of the music you search, or what is the correct sound effect for something. Be able to play musics and sounds directly in editor could be a little time saver than open files in a media player, find the correct one and go back to the editor to select it.

**Comment by christopho** [comment]
This will be easy to implement now that the quest editor uses the Solarus library.

**Comment by oclero** [comment]
A double-clic on the sound or music could play it (i mean : no need to open a tab for each sound resource). What do you think ?

**Comment by Diarandor** [comment]
I think that both, double click and also an option in the context menu (right click), would be useful.

**Comment by Diarandor** [comment]
Also, allow to stop playing a song or sound may be important, so we do not need to wait it to end.
Or otherwise just play the songs in the default player, so it can be stopped.
