### ISSUE TITLE
Options that will be very useful for makers:

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#84]
- Add shortcuts (spacebar) to move the map as in photoshop, it's more useful for game designers in addition to the scroll wheel.
- Add button to reload the tilesets in the tabs of tilesets such as tabs maps.
- Add buttons in the toolbar, to create a new quest or open a current quest.

Je ne suis pas fort en anglais du coup je te laisse le dernier point en Français:

- En plus des raccourcis (B et T), se serait utile de permettre la disposition des tilesets plan par plan, comme on n'a que deux possibilités (B et T) ça prend beaucoup de temps pour arranger un tilesets dans le 4ème plan par exemple.

**Comment by christopho** [comment]
1) 2) Je viens d'ouvrir #85 et #86 pour les deux premières suggestions.
3) Je suis moins sûr de l'intérêt d'avoir des boutons supplémentaires pour créer une nouvelle quête ou en ouvrir une existante. On ne fait pas cela souvent.
4) J'ai pas bien compris, même en français :) Tu parles de tilesets ou de tiles ?

**Comment by maxamine** [comment]
Salut Christopho,
Concernant le dernier point, je parle des tiles dans la map, Dans Solarus quest editor on n'a que 2 possibilités, soit les mettre au premier plan ou en arrière plan, Se serait utile si on avait la possibilité de la disposition en avant ou en arrière, plan par plan. L'image ci-dessous explique ce que je dis.
![sans titre-2](https://cloud.githubusercontent.com/assets/14140919/9722911/b82d8122-55ad-11e5-9dc9-f74b108dbb69.png)

**Comment by christopho** [comment]
Ok je comprends, c'est vrai que cela peut-être utile. J'ai ouvert une autre issue: #87
Je ferme donc celle-ci. N'hésite pas à ouvrir une issue différente pour chaque suggestion pour les prochaines fois :)
