### ISSUE TITLE
Allow to cancel putting a tile in the map with (escape key)

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#92]
When we take a tile from the tileset to put it in the map and we decide to cancel the operation we must  click on an empty spot in the tileset or put the tile in the map then delete it. it would be nice if we can cancel the operation just with the (escape key).

**Comment by christopho** [comment]
Good point. Ctrl-Z cancels the last action but the entity under the mouse remains Escape is a good suggestion.
