### ISSUE TITLE
Allow to add more than 3 tiles for each animated tile.

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#95]
in solarus quest editor 1.4.4 we can't add more than 3 tiles for each animated tile, it would be useful to put more than 3 tiles to have realistic animations. see the print screen below.

![sans titre](https://cloud.githubusercontent.com/assets/14140919/9742431/ef3e05a6-5657-11e5-93ef-d58fadd89c6e.png)

**Comment by Maxs1789** [comment]
That's a limitation of the engine, so the behavior of the editor is normal.

See [solarus#683](https://github.com/christopho/solarus/issues/683).

**Comment by maxamine** [comment]
ya i saw it

**Comment by christopho** [comment]
Duplicate of the engine one.
