### ISSUE TITLE
Allow to add multiple worktops in the same window (map editor).

### ISSUE THREAD

**Issue by maxamine** [christopho/solarus-quest-editor#97]
it will help to have a clear vision on the linked maps and allows to work with an overview on them (such as inside and outside house maps). See the print screen below.

![sans titre](https://cloud.githubusercontent.com/assets/14140919/9745420/b0c9ec60-5669-11e5-99b4-25a51143b961.jpg)

**Comment by christopho** [comment]
I don't get it. You want to display another map in the tab of a map?

**Comment by maxamine** [comment]
yes, if we can include 2 maps in the same tab, it will help to work with an overview on them. with this option we will no longer have to switch between 2 tabs of linked  maps for exemple since we have overview on both of them.

**Comment by Renkineko** [comment]
How do you choose the map on the side ?

**Comment by maxamine** [comment]
can you explain you're question?

**Comment by christopho** [comment]
I'm not convinced. One tab, one file.

**Comment by Renkineko** [comment]
@maxamine : you say include 2 maps in the same tab, but if you have a map connected with 6 maps, you will not show 7 maps, so if your goal is to have 2 maps (and only 2 : a "main" map et a map connected), how do you choose the connected map ?

I think a shortcut on a teleporter to open the corresponding map can be very useful, but display two maps in the same layout ? Not sure of the utility.

**Comment by maxamine** [comment]
hmmmm, may be with shortcuts to switch quickly between opened maps will be more useful as christopho said

**Comment by christopho** [comment]
Ok, I will open another issue for shortcuts and let's close this one.
